apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: helm-guestbook
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    chart: helm-guestbook
    repoURL: https://hardikchakravarti.github.io/chartrepository/helm-guestbook
    targetRevision: 0.1.0
    helm:
      valueFiles:
      - $values/helm-guestbook/values.yaml
  - repoURL: 'https://github.com/hardikchakravarti/helm-example.git'
